FROM mcr.microsoft.com/devcontainers/python:1-3.11-bookworm

RUN pip install poetry==1.7.1

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache
ENV XMLTV_URL=
ENV TZ=
ENV PORT=